routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'DocumentController@index')->name('index');
Route::resource('/document', 'DocumentController', ['except' => ['index']] );

Route::resource('/commentary', 'CommentaryController', ['except' => ['index']] );


Route::get('users', 'UserController@getInfos');
Route::post('users', 'UserController@postInfos');

Route::get('contact', 'ContactController@getForm');
Route::post('contact', 'ContactController@postForm');

Route::get('photo', 'PhotoController@getForm');
Route::post('photo', 'PhotoController@postForm');

Route::get('newsletter', 'EmailController@getForm');
Route::post('newsletter', ['uses' => 'EmailController@postForm', 'as' => 'storeEmail']);

Route::resource('user', 'UserController');

//Route::get('newsletter/', 'newsletter/newsletter');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/article/add.blade.php
@extends('base')

@section('content')
    <br>
    <div class="col-sm-offset-3 col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">Add an article</div>
            <div class="panel-body">
                {!! Form::open(['route' => 'document.store', 'files' => true]) !!}
                <div class="form-group {!! $errors->has('title') ? 'has-error' : '' !!}">
                    {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title']) !!}
                    {!! $errors->first('title', '<small class="help-block">:message</small>') !!}
                </div>
                <div class="form-group {!! $errors->has('category') ? 'has-error' : '' !!}">

                    <select name="category_id" id="category" class="form-control">
                        @foreach($categories as $id => $country)
                            <option value="{{ $id }}">
                                {{ $country -> name }}
                            </option>
                        @endforeach
                    </select>
                    {!! $errors->first('category', '<small class="help-block">:message</small>') !!}
                </div>
                <div class="form-group {!! $errors->has('description') ? 'has-error' : '' !!}">
                    {!! Form::textarea ('description', null, ['class' => 'form-control', 'placeholder' => 'Description']) !!}
                    {!! $errors->first('description', '<small class="help-block">:message</small>') !!}
                </div>
                <div class="form-group {!! $errors->has('img') ? 'has-error' : '' !!}">
                    {!! Form::file('img', ['class' => 'form-control']) !!}
                    {!! $errors->first('img', '<small class="help-block">:message</small>') !!}
                </div>
                {!! Form::submit('Send', ['class' => 'btn btn-info pull-right']) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/article/article.blade.php
@extends('base')

@section('content')
    @if(isset($info))
        <div class="row alert alert-info">{{ $info }}</div>
    @endif
    {!! $links !!}
    @foreach($posts as $post)
        <article class="row bg-primary-dark">
            <div class="col-md-12">
                <header>
{{--                    <h1>  {!! link_to('document/'.$post->id, $post->title) !!}--}}
                        <h1><a href="{{route('document.show', $post ?? '')}}"  role="button">{{$post->title}}</a> </h1>
                </header>
                <hr>
                <section>
                    <p>{{ $post->description }}</p>
                    @if(Auth::check() and Auth::user()->admin)
                        {!! Form::open(['method' => 'DELETE', 'route' => ['document.destroy', $post->id]]) !!}
                        {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-xs ', 'onclick' => 'return confirm(\'Vraiment supprimer cet article ?\')']) !!}
                        {!! Form::close() !!}
                    @endif
                    <em class="pull-right">
                        <span class="glyphicon glyphicon-pencil"></span> {{ $post->user->name }} le{!! $post->date !!}
                    </em>
                </section>
            </div>
        </article>
        <br>
    @endforeach
{!! $links !!}
@endsection

resources/views/article/detail.blade.php
@extends('base')

@section('header')
    @if(Auth::check())
        <div class="btn-group pull-right">
            {!! link_to_route('document.create', 'Create an article', [], ['class' => 'btn btn-info']) !!}
            {!! link_to('logout', 'Logout', ['class' => 'btn btn-warning']) !!}
        </div>
    @else
        {!! link_to('login', 'Connect', ['class' => 'btn btn-info pull-right']) !!}
    @endif
@endsection

@section('content')

    @if($post)

        <article class="row bg-primary-dark">
            <div class="col-md-12">

                <header>
                        <h3>{{$post->title}}</h3>
                </header>
                <hr>
                <section>
                    <p>{{ $post->description }}</p>
                    <em class="pull-right">
                        <span class="glyphicon glyphicon-pencil"></span> {{ $post->user->name }} le{!! $post->date !!}
                    </em>
                </section><br>

                    @if(Auth::check())
                        <p>
                            <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                                Leave a comment
                            </a>

                        </p>
                        <div class="collapse" id="collapseExample">
                            <div class="card card-body">
                                {!! Form::open(['route' => 'commentary.store']) !!}
                                <div class="form-group {!! $errors->has('title') ? 'has-error' : '' !!}">
                                    {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title']) !!}
                                    {!! $errors->first('title', '<small class="help-block">:message</small>') !!}
                                </div>
                                <div class="form-group {!! $errors->has('description') ? 'has-error' : '' !!}">
                                    {!! Form::textarea ('description', null, ['class' => 'form-control', 'placeholder' => 'Description']) !!}
                                    {!! $errors->first('description', '<small class="help-block">:message</small>') !!}
                                </div>
                                {{ Form::hidden('document_id', $post->id ) }}
                                {!! Form::submit('Send', ['class' => 'btn btn-info pull-right']) !!}
                                {!! Form::close() !!}
                            </div>
                        </div><br><br><br>
                    @endif

                <div class="float-right">
                    @if($comments)
                        @foreach($comments as $com)
                            <header><h5>Commentaire n° {{$com->id}}</h5></header>
                            <h6>{{$com->title}}</h6>
                            <p>{{$com->description}}</p>
                            <p>{{$com->date}}</p>
                            @endforeach
                        @endif
                </div><br>



            </div>
        </article>
        @endif
        <br>


@endsection

resources/views/article/photo.blade.php
@extends('base')

@section('content')
    <br>
    <div class="col-sm-offset-4 col-sm-4">
        <div class="panel panel-info">
            <div class="panel-heading">Envoi d'une photo</div>
            <div class="panel-body">
                @if(session()->has('error'))
                    <div class="alert alert-danger">{!! session('error') !!}</div>
                @endif
                {!! Form::open(['url' => 'photo', 'files' => true]) !!}
                <div class="form-group {!! $errors->has('image') ? 'has-error' : '' !!}">
                    {!! Form::file('image', ['class' => 'form-control']) !!}
                    {!! $errors->first('image', '<small class="help-block">:message</small>') !!}
                </div>
                {!! Form::submit('Envoyer !', ['class' => 'btn btn-info pull-right']) !!}
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection